In [1]:
import pickle

In [2]:
with open("scaler1.pkl","rb") as file:
    loaded_scaler1=pickle.load(file)

In [3]:
with open("lr1.pkl","rb") as file:
    loaded_model1=pickle.load(file)

In [5]:
import numpy as np
import pandas as pd
manuel_ozellikler = [17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871, 1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193, 25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189]



In [8]:
manuel_df=pd.DataFrame([manuel_ozellikler])

In [9]:
manuel_df

0      1      2     3       4       5       6       7       8        9   \
0  17.99  10.38  122.8  1001  0.1184  0.2776  0.3001  0.1471  0.2419  0.07871   

   ...     20     21     22    23      24      25      26      27      28  \
0  ...  25.38  17.33  184.6  2019  0.1622  0.6656  0.7119  0.2654  0.4601   

       29  
0  0.1189  

[1 rows x 30 columns]

In [13]:
manuel_olceklendirilmis_veri=loaded_scaler1.transform(manuel_df)

C:\Users\kaaaaaaa\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 1.11395317, -2.05194746,  1.28984408,  1.01246402,  1.55730869,
         3.21796293,  2.64033262,  2.53477785,  2.17466689,  2.25653856,
         2.61697842, -0.57659192,  2.96486713,  2.73067913, -0.20410978,
         1.28507913,  0.69855981,  0.6603744 ,  1.16583326,  0.88740624,
         1.91720406, -1.36808715,  2.34141741,  2.06085187,  1.27943934,
         2.47442113,  2.04655848,  2.28342641,  2.62536852,  1.84002385]])

In [14]:
loaded_model1.predict(manuel_olceklendirilmis_veri)

array([1], dtype=int64)

In [16]:
if loaded_model1.predict(manuel_olceklendirilmis_veri)==1:
    print("verilen değerlere göre tahmin edilen durum kanserli",loaded_model1.predict(manuel_olceklendirilmis_veri))
else:
    print("verilen değerlere göre tahmin edilen durum kanserli değil",loaded_model1.predict(manuel_olceklendirilmis_veri))

verilen değerlere göre tahmin edilen durum kanserli [1]


In [18]:
import joblib
with open("scaler5.jb","rb") as file:
    loaded_scaler2=joblib.load(file)
    
with open("lr5.jb","rb") as file:
    loaded_model2=joblib.load(file)

In [19]:
import numpy as np
import pandas as pd
manuel_ozellikler = [17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871, 1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193, 25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189]



In [20]:
manuel_df=pd.DataFrame([manuel_ozellikler])

In [21]:
manuel_olceklendirilmis_veri=loaded_scaler2.transform(manuel_df)

C:\Users\kaaaaaaa\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [22]:
loaded_model2.predict(manuel_olceklendirilmis_veri)

array([1], dtype=int64)

In [23]:
if loaded_model2.predict(manuel_olceklendirilmis_veri)==1:
    print("verilen değerlere göre tahmin edilen durum kanserli",loaded_model2.predict(manuel_olceklendirilmis_veri))
else:
    print("verilen değerlere göre tahmin edilen durum kanserli değil",loaded_model2.predict(manuel_olceklendirilmis_veri))

verilen değerlere göre tahmin edilen durum kanserli [1]
